name: Sync markdown files to notion
description: Github action for pushing markdown changes to Notion
author: step-security
inputs:
  notion-token:
    description: 'Notion integration token for authorization'
    required: true
branding:
  color: yellow
  icon: pencil
runs:
  using: 'node20'
  main: 'dist/index.js'
